"""Generate the rsyslog tenant-map.txt for the Sophos syslog receiver.

Reads firewall WAN IPs from the most recent daily pull
(technijian/sophos-pull/<latest>/firewalls_all.json) and emits two files:

    state/sophos-tenant-ipmap.txt   human-friendly two-column file
                                    (<wan_ip>  <tenant_code>) used by the rsyslog
                                    rebuild-sophos-tenant-map helper script.

    state/sophos-tenant-ipmap.json  rsyslog lookup-table format (consumed
                                    directly by lookup_table() in the receiver
                                    config). Same data, lookup-ready.

Run after pull_sophos_daily.py succeeds. The receiver is expected to scp/rsync
the .json down (or this script is run on the receiver itself with the repo
checked out / mounted).

Usage:
    python seed_tenant_map.py                 # use latest daily pull
    python seed_tenant_map.py --date 2026-04-29
    python seed_tenant_map.py --out /etc/rsyslog.d/sophos/tenant-map.json
    python seed_tenant_map.py --print         # stdout only, no write
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PIPELINE_ROOT = HERE.parent
STATE_DIR = PIPELINE_ROOT / "state"
TXT_OUT = STATE_DIR / "sophos-tenant-ipmap.txt"
JSON_OUT = STATE_DIR / "sophos-tenant-ipmap.json"


def latest_run_dir() -> Path | None:
    candidates = sorted(
        (p for p in PIPELINE_ROOT.iterdir() if p.is_dir() and len(p.name) == 10 and p.name[4] == "-"),
        reverse=True,
    )
    return candidates[0] if candidates else None


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Seed rsyslog tenant-map from Sophos firewall inventory.")
    ap.add_argument("--date", help="YYYY-MM-DD daily pull dir (default: latest)")
    ap.add_argument("--out", help="Write JSON to this path instead of state/sophos-tenant-ipmap.json")
    ap.add_argument("--out-txt", help="Write TXT to this path instead of state/sophos-tenant-ipmap.txt")
    ap.add_argument("--print", action="store_true", help="Print to stdout, do not write files")
    return ap.parse_args()


def main() -> int:
    args = parse_args()

    if args.date:
        run_dir = PIPELINE_ROOT / args.date
    else:
        run_dir = latest_run_dir()
    if not run_dir or not run_dir.exists():
        print(f"ERR: no daily run directory found (run pull_sophos_daily.py first)")
        return 2
    fwfile = run_dir / "firewalls_all.json"
    if not fwfile.exists():
        print(f"ERR: {fwfile} not found")
        return 2
    fws = json.loads(fwfile.read_text(encoding="utf-8"))

    rows: list[tuple[str, str, str, str]] = []
    seen: set[tuple[str, str]] = set()
    for fw in fws:
        ips = fw.get("externalIpv4Addresses") or []
        if not ips and fw.get("externalIpv4Address"):
            ips = [fw["externalIpv4Address"]]
        code = (fw.get("LocationCode") or "").lower()
        serial = fw.get("serialNumber", "")
        host = fw.get("hostname") or fw.get("name") or serial
        for ip in ips:
            if not ip or not code:
                continue
            key = (ip, code)
            if key in seen:
                continue
            seen.add(key)
            rows.append((ip, code, serial, host))
    rows.sort()

    txt_lines = [
        "# Auto-generated by seed_tenant_map.py from the latest pull_sophos_daily run.",
        f"# Source: {fwfile}",
        f"# Firewalls covered: {len(rows)}",
        "# Format: <wan_ip>  <tenant_code>   (third + fourth columns are comments)",
        "",
    ]
    txt_lines.extend(f"{ip:<18s}{code:<8s}# {serial}  {host}" for ip, code, serial, host in rows)
    txt = "\n".join(txt_lines) + "\n"

    table = {
        "version": 1,
        "nomatch": "unk",
        "type": "string",
        "table": [{"index": ip, "value": code} for ip, code, _, _ in rows],
    }
    js = json.dumps(table, indent=2)

    if args.print:
        print(txt)
        print("---")
        print(js)
        return 0

    txt_path = Path(args.out_txt) if args.out_txt else TXT_OUT
    js_path = Path(args.out) if args.out else JSON_OUT
    txt_path.parent.mkdir(parents=True, exist_ok=True)
    js_path.parent.mkdir(parents=True, exist_ok=True)
    txt_path.write_text(txt, encoding="utf-8")
    js_path.write_text(js + "\n", encoding="utf-8")

    print(f"  wrote: {txt_path}  ({len(rows)} firewalls)")
    print(f"  wrote: {js_path}")
    print()
    print("Next step (on the rsyslog receiver):")
    print("  scp <repo>/technijian/sophos-pull/state/sophos-tenant-ipmap.json \\")
    print("      <user>@siem-ingest.technijian.com:/etc/rsyslog.d/sophos/tenant-map.json")
    print("  ssh <user>@siem-ingest.technijian.com 'sudo systemctl reload rsyslog'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
